package com.maheffa.TabulatedOCR.DBManager;


import java.util.HashSet;
import java.util.Set;

/**
 * TableFormat generated by hbm2java
 */
public class TableFormat implements java.io.Serializable {

	private Integer idTableFormat;
	private Format format;
	private Integer columnCount;
	private Boolean readFirstLine;
	private Set columnCharacteristics = new HashSet(0);

	public TableFormat() {
	}

	public TableFormat(Format format, Integer columnCount,
			Boolean readFirstLine, Set columnCharacteristics) {
		this.format = format;
		this.columnCount = columnCount;
		this.readFirstLine = readFirstLine;
		this.columnCharacteristics = columnCharacteristics;
	}

	public Integer getIdTableFormat() {
		return this.idTableFormat;
	}

	public void setIdTableFormat(Integer idTableFormat) {
		this.idTableFormat = idTableFormat;
	}

	public Format getFormat() {
		return this.format;
	}

	public void setFormat(Format format) {
		this.format = format;
	}

	public Integer getColumnCount() {
		return this.columnCount;
	}

	public void setColumnCount(Integer columnCount) {
		this.columnCount = columnCount;
	}

	public Boolean getReadFirstLine() {
		return this.readFirstLine;
	}

	public void setReadFirstLine(Boolean readFirstLine) {
		this.readFirstLine = readFirstLine;
	}

	public Set getColumnCharacteristics() {
		return this.columnCharacteristics;
	}

	public void setColumnCharacteristics(Set columnCharacteristics) {
		this.columnCharacteristics = columnCharacteristics;
	}

    @Override
    public String toString() {
        StringBuilder str = new StringBuilder();
        str.append("{TableFormat: ncolumns=").append(columnCount)
                .append(", read first line=").append(readFirstLine ? "yes" : "no")
                .append("}");
        return str.toString();
    }
}
