// default package
// Generated May 22, 2015 4:03:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Format generated by hbm2java
 */
public class Format implements java.io.Serializable {

	private Integer idFormat;
	private String type;
	private String name;
	private Set textFormats = new HashSet(0);
	private Set tableFormats = new HashSet(0);

	public Format() {
	}

	public Format(String name) {
		this.name = name;
	}

	public Format(String type, String name, Set textFormats, Set tableFormats) {
		this.type = type;
		this.name = name;
		this.textFormats = textFormats;
		this.tableFormats = tableFormats;
	}

	public Integer getIdFormat() {
		return this.idFormat;
	}

	public void setIdFormat(Integer idFormat) {
		this.idFormat = idFormat;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getTextFormats() {
		return this.textFormats;
	}

	public void setTextFormats(Set textFormats) {
		this.textFormats = textFormats;
	}

	public Set getTableFormats() {
		return this.tableFormats;
	}

	public void setTableFormats(Set tableFormats) {
		this.tableFormats = tableFormats;
	}

}
