// default package
// Generated May 22, 2015 4:03:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * Ocrconfig generated by hbm2java
 */
public class Ocrconfig implements java.io.Serializable {

	private Integer idOcrconfig;
	private String name;
	private Integer dpi;
	private String language;
	private Integer grayscale;
	private Boolean binarisation;
	private Integer margin;
	private Integer radius;
	private Integer threshold1;
	private Integer threshold2;
	private Integer distanceAccumulation;
	private Double angleAccumulation;
	private Integer thresholdAccumulation;
	private Integer minLenght;
	private Integer maxGap;
	private Double tolerableSkewAngle;
	private Integer maxLineDistance;
	private Integer maxLineGap;
	private Integer lineThickness;
	private Boolean deskew;
	private Boolean denoise;
	private Boolean userDictionary;

	public Ocrconfig() {
	}

	public Ocrconfig(String name) {
		this.name = name;
	}

	public Ocrconfig(String name, Integer dpi, String language,
			Integer grayscale, Boolean binarisation, Integer margin,
			Integer radius, Integer threshold1, Integer threshold2,
			Integer distanceAccumulation, Double angleAccumulation,
			Integer thresholdAccumulation, Integer minLenght, Integer maxGap,
			Double tolerableSkewAngle, Integer maxLineDistance,
			Integer maxLineGap, Integer lineThickness, Boolean deskew,
			Boolean denoise, Boolean userDictionary) {
		this.name = name;
		this.dpi = dpi;
		this.language = language;
		this.grayscale = grayscale;
		this.binarisation = binarisation;
		this.margin = margin;
		this.radius = radius;
		this.threshold1 = threshold1;
		this.threshold2 = threshold2;
		this.distanceAccumulation = distanceAccumulation;
		this.angleAccumulation = angleAccumulation;
		this.thresholdAccumulation = thresholdAccumulation;
		this.minLenght = minLenght;
		this.maxGap = maxGap;
		this.tolerableSkewAngle = tolerableSkewAngle;
		this.maxLineDistance = maxLineDistance;
		this.maxLineGap = maxLineGap;
		this.lineThickness = lineThickness;
		this.deskew = deskew;
		this.denoise = denoise;
		this.userDictionary = userDictionary;
	}

	public Integer getIdOcrconfig() {
		return this.idOcrconfig;
	}

	public void setIdOcrconfig(Integer idOcrconfig) {
		this.idOcrconfig = idOcrconfig;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getDpi() {
		return this.dpi;
	}

	public void setDpi(Integer dpi) {
		this.dpi = dpi;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public Integer getGrayscale() {
		return this.grayscale;
	}

	public void setGrayscale(Integer grayscale) {
		this.grayscale = grayscale;
	}

	public Boolean getBinarisation() {
		return this.binarisation;
	}

	public void setBinarisation(Boolean binarisation) {
		this.binarisation = binarisation;
	}

	public Integer getMargin() {
		return this.margin;
	}

	public void setMargin(Integer margin) {
		this.margin = margin;
	}

	public Integer getRadius() {
		return this.radius;
	}

	public void setRadius(Integer radius) {
		this.radius = radius;
	}

	public Integer getThreshold1() {
		return this.threshold1;
	}

	public void setThreshold1(Integer threshold1) {
		this.threshold1 = threshold1;
	}

	public Integer getThreshold2() {
		return this.threshold2;
	}

	public void setThreshold2(Integer threshold2) {
		this.threshold2 = threshold2;
	}

	public Integer getDistanceAccumulation() {
		return this.distanceAccumulation;
	}

	public void setDistanceAccumulation(Integer distanceAccumulation) {
		this.distanceAccumulation = distanceAccumulation;
	}

	public Double getAngleAccumulation() {
		return this.angleAccumulation;
	}

	public void setAngleAccumulation(Double angleAccumulation) {
		this.angleAccumulation = angleAccumulation;
	}

	public Integer getThresholdAccumulation() {
		return this.thresholdAccumulation;
	}

	public void setThresholdAccumulation(Integer thresholdAccumulation) {
		this.thresholdAccumulation = thresholdAccumulation;
	}

	public Integer getMinLenght() {
		return this.minLenght;
	}

	public void setMinLenght(Integer minLenght) {
		this.minLenght = minLenght;
	}

	public Integer getMaxGap() {
		return this.maxGap;
	}

	public void setMaxGap(Integer maxGap) {
		this.maxGap = maxGap;
	}

	public Double getTolerableSkewAngle() {
		return this.tolerableSkewAngle;
	}

	public void setTolerableSkewAngle(Double tolerableSkewAngle) {
		this.tolerableSkewAngle = tolerableSkewAngle;
	}

	public Integer getMaxLineDistance() {
		return this.maxLineDistance;
	}

	public void setMaxLineDistance(Integer maxLineDistance) {
		this.maxLineDistance = maxLineDistance;
	}

	public Integer getMaxLineGap() {
		return this.maxLineGap;
	}

	public void setMaxLineGap(Integer maxLineGap) {
		this.maxLineGap = maxLineGap;
	}

	public Integer getLineThickness() {
		return this.lineThickness;
	}

	public void setLineThickness(Integer lineThickness) {
		this.lineThickness = lineThickness;
	}

	public Boolean getDeskew() {
		return this.deskew;
	}

	public void setDeskew(Boolean deskew) {
		this.deskew = deskew;
	}

	public Boolean getDenoise() {
		return this.denoise;
	}

	public void setDenoise(Boolean denoise) {
		this.denoise = denoise;
	}

	public Boolean getUserDictionary() {
		return this.userDictionary;
	}

	public void setUserDictionary(Boolean userDictionary) {
		this.userDictionary = userDictionary;
	}

}
