// default package
// Generated May 22, 2015 4:03:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private Integer idProject;
	private String name;
	private String inputFilePath;

	public Project() {
	}

	public Project(String name) {
		this.name = name;
	}

	public Project(String name, String inputFilePath) {
		this.name = name;
		this.inputFilePath = inputFilePath;
	}

	public Integer getIdProject() {
		return this.idProject;
	}

	public void setIdProject(Integer idProject) {
		this.idProject = idProject;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getInputFilePath() {
		return this.inputFilePath;
	}

	public void setInputFilePath(String inputFilePath) {
		this.inputFilePath = inputFilePath;
	}

}
